-- email-verify-mcp schema (standalone email-verify Supabase project). Idempotent.
--
-- Tables:
--   email_domain_cache — per-domain verification facts (7-day cache)
--   ev_query_usage     — per-agent/day free-tier counter (+ ev_claim_free_query)
--   ev_payments        — verified x402 payments ledger (double-spend guard)
--   ev_verify_log      — lightweight per-verification log (daily brief stats)
--   daily_briefs       — curated daily brief (+ increment_brief_purchase)

-- ── email_domain_cache ────────────────────────────────────────────────────────
create table if not exists email_domain_cache (
  domain          text primary key,
  mx_valid        boolean,
  mx_hosts        jsonb,
  disposable      boolean,
  free_provider   boolean,
  domain_age_days integer,
  last_checked    timestamptz not null default now()
);
create index if not exists idx_edc_last_checked on email_domain_cache (last_checked);

-- ── ev_verify_log (daily brief stats) ─────────────────────────────────────────
create table if not exists ev_verify_log (
  id          bigint generated by default as identity primary key,
  domain      text,
  disposable  boolean,
  deliverable text,
  created_at  timestamptz not null default now()
);
create index if not exists idx_evlog_created on ev_verify_log (created_at desc);
create index if not exists idx_evlog_domain  on ev_verify_log (domain);

-- ── ev_query_usage (free-tier counter) ────────────────────────────────────────
create table if not exists ev_query_usage (
  agent_key   text not null,
  day         date not null,
  count       integer not null default 0,
  updated_at  timestamptz not null default now(),
  primary key (agent_key, day)
);

-- ── ev_payments (x402 ledger / double-spend guard) ────────────────────────────
create table if not exists ev_payments (
  tx_signature  text primary key,
  intent        text,
  agent_key     text,
  tool          text,
  amount_usdc   numeric,
  payer_wallet  text,
  recipient     text,
  status        text,
  block_time    bigint,
  created_at    timestamptz not null default now()
);

-- ── daily_briefs ──────────────────────────────────────────────────────────────
create table if not exists daily_briefs (
  brief_date        date primary key,
  brief_data        jsonb not null,
  signal_count      integer not null default 0,
  attestation_hash  text,
  purchase_count    integer not null default 0,
  expires_at        timestamptz,
  created_at        timestamptz not null default now()
);

-- Atomically claim ONE free query for (agent_key, day) only if under the cap.
create or replace function ev_claim_free_query(p_agent_key text, p_day date, p_cap integer)
returns jsonb language plpgsql as $$
declare cur integer; ok boolean;
begin
  insert into ev_query_usage (agent_key, day, count, updated_at)
  values (p_agent_key, p_day, 0, now())
  on conflict (agent_key, day) do nothing;

  select count into cur from ev_query_usage
    where agent_key = p_agent_key and day = p_day for update;

  if cur < p_cap then
    update ev_query_usage set count = count + 1, updated_at = now()
      where agent_key = p_agent_key and day = p_day;
    ok := true; cur := cur + 1;
  else
    ok := false;
  end if;
  return jsonb_build_object('allowed', ok, 'count', cur, 'cap', p_cap);
end;
$$;

create or replace function increment_brief_purchase(p_brief_date date)
returns void language sql as $$
  update daily_briefs set purchase_count = purchase_count + 1 where brief_date = p_brief_date;
$$;
